Feature/auth update
towa-digital/sprint-slides-generator pull request #15
Opened 2022-08-30 07:18 UTC by Michiocre

Updated to jira oauth 2.0
Added Bugs page in the presentation

2022-08-30 08:02 UTC, mattcrn commented on pages/api/oauth/callback.js
> +  // const cloudResponse = await fetch(
I guess we can remove that

2022-08-30 08:04 UTC, mattcrn commented on pages/api/sprints/active.js
> +    // const data = [...apiData, ...dbData].filter((sprint) =>
Is this not needed anymore? then lets remove it

2022-08-30 08:39 UTC, Michiocre commented on .env.example
> +API_URL='https://api.atlassian.com/ex/jira/'
See https://github.com/towa-digital/sprint-slides-generator/pull/15/commits/7e291508d3f67e238e0c4478688b939330a01435

2022-08-30 08:39 UTC, Michiocre commented on pages/api/sprints/active.js
> +    // const data = [...apiData, ...dbData].filter((sprint) =>
See https://github.com/towa-digital/sprint-slides-generator/pull/15/commits/14875f7b2f7cb87c0a537c182b4e1386ebd0d12f

2022-08-30 08:39 UTC, Michiocre commented on pages/api/oauth/callback.js
> +  // const cloudResponse = await fetch(
See https://github.com/towa-digital/sprint-slides-generator/pull/15/commits/14875f7b2f7cb87c0a537c182b4e1386ebd0d12f

2022-09-01 08:17 UTC, Gabsii requested changes

2022-09-01 08:17 UTC, Gabsii commented on utils/jiraApi.js
> +const cloudId = '918d98df-4747-4c9d-b197-d7d658581d27';
move to .env if this is sensitive data

2022-09-01 08:17 UTC, Gabsii commented on utils/sprintMetrics.js
> +  }
if we have bugs and other types of tickets we won't return the others correctly this way

2022-09-01 08:17 UTC, Gabsii commented on pages/api/oauth/redirect.js
> +    `https://auth.atlassian.com/authorize?audience=api.atlassian.com&client_id=V27DQrIWINbWI9VuSOcxI6QVPptPQsks&scope=read%3Asprint%3Ajira-software%20read%3Agroup%3Ajira%20read%3Aapplication-role%3Aj
move client_id redirect_id to .env

2022-09-01 08:17 UTC, Gabsii commented on pages/api/oauth/redirect.js
> +  //%20offline_access add this scope to enable refresh token
remove comment

2022-09-01 08:17 UTC, Gabsii commented on pages/boards.jsx
> +  let expiresAt = sessionData(req, res, 'expiresAt');
we don't refresh so we don't need this in the session

2022-09-01 08:17 UTC, Gabsii commented on pages/dashboard.jsx
> +  let expiresAt = new Date(sessionData(req, res, 'expiresAt'));
same here. 
IMO the user should just be redirected if something fails in regards to the authtoken

2022-09-01 08:17 UTC, Gabsii commented on pages/index.jsx
> +import { Button } from '@zeit-ui/react';
we're not using a button here

2022-09-01 08:17 UTC, Gabsii commented on pages/sprint/[slug].jsx
> +  memoCurrentSprint.title = memoCurrentSprint.sprintName + ' | SprintGenerator'
this should happen in the use memo itself

2022-09-01 09:05 UTC, Michiocre commented on pages/boards.jsx
> +  let expiresAt = sessionData(req, res, 'expiresAt');
I still use expiresAt to redirect the user before a invalid request is made

2022-09-02 12:29 UTC, Gabsii commented on pages/boards.jsx
> +    };
since this is used in multiple places - can we maybe move it to a function that takes req and res and returns the props?

2022-09-02 14:11 UTC, Gabsii approved these changes

2022-09-02 14:12 UTC, merged