Release 0.0.5
towa-digital/sprint-slides-generator pull request #17
Opened 2022-09-06 14:41 UTC by Michiocre

### Updated

- The login now works using jira oauth 2.0
- Issues are sorted by assignee

### Added

- Change Requests will now be displayed as well as Improvents
- Bugs will now also be displayed

### Fixed

- Fixed bug where sprints weren't aligned with the boards
- redirect unauthed user to login
- Fixed a bug where the intro slides background was missing

2022-09-13 22:20 UTC, Gabsii requested changes

2022-09-13 22:20 UTC, Gabsii commented on pages/api/oauth/redirect.js
> +  console.log(process.env);
remove console.log

2022-09-19 13:48 UTC, Michiocre commented on pages/api/oauth/redirect.js
> +  console.log(process.env);
Fixed

2022-09-19 14:35 UTC, Gabsii requested changes

2022-09-19 14:35 UTC, Gabsii commented on components/SavePresentation.jsx
> +          presenter. No one else will be able to edit this persentation in the
typo

2022-09-19 14:42 UTC, merged